'use strict';

const PROVENANCE_SCHEMA_VERSION = 1;

const PROVENANCE_STATUS = Object.freeze({
  DRAFT: 'draft',
  PUBLISHED: 'published',
  ARCHIVED: 'archived',
});

const PROVENANCE_STATUSES = Object.freeze(
  Object.values(PROVENANCE_STATUS)
);

const ARTISAN_LIMITS = Object.freeze({
  ARTISAN_CODE_MAX_LENGTH: 64,
  DISPLAY_NAME_MAX_LENGTH: 120,
  CRAFT_TYPE_MAX_LENGTH: 120,
  VILLAGE_MAX_LENGTH: 120,
  DISTRICT_MAX_LENGTH: 120,
  STATE_MAX_LENGTH: 120,
  COUNTRY_MAX_LENGTH: 80,
  LOOM_TYPE_MAX_LENGTH: 120,
});

const PROVENANCE_LIMITS = Object.freeze({
  DOCUMENT_ID_MAX_LENGTH: 128,
  MATERIAL_MAX_LENGTH: 160,
  WEAVE_TECHNIQUE_MAX_LENGTH: 160,
  LOOM_TYPE_MAX_LENGTH: 120,
  ORIGIN_VILLAGE_MAX_LENGTH: 120,
  ORIGIN_DISTRICT_MAX_LENGTH: 120,
  ORIGIN_STATE_MAX_LENGTH: 120,
  ORIGIN_COUNTRY_MAX_LENGTH: 80,
});

module.exports = {
  PROVENANCE_SCHEMA_VERSION,
  PROVENANCE_STATUS,
  PROVENANCE_STATUSES,
  ARTISAN_LIMITS,
  PROVENANCE_LIMITS,
};
