const { ROLES } = require("./roles");
const { PERMISSIONS } = require("./permissions");

/**
 * Enterprise Role → Permission Mapping
 *
 * Principle:
 * - Roles define identity.
 * - Permissions define authority.
 * - Middleware must authorize using permissions.
 */

const ROLE_PERMISSIONS = Object.freeze({

  [ROLES.OWNER]: ["*"],

  [ROLES.SUPER_ADMIN]: [
    "*"
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PRODUCTS_DELETE,

    PERMISSIONS.CATEGORIES_CREATE,
    PERMISSIONS.CATEGORIES_UPDATE,

    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,

    PERMISSIONS.USERS_READ,

    PERMISSIONS.VENDORS_APPROVE,

    PERMISSIONS.REPORTS_READ,

    PERMISSIONS.ANALYTICS_READ
  ],

  [ROLES.VENDOR]: [
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_UPDATE,

    PERMISSIONS.ORDERS_READ,

    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ORDERS_READ
  ],

  [ROLES.DELIVERY_PARTNER]: [
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.DELIVERIES_READ,
    PERMISSIONS.DELIVERIES_UPDATE
  ],

  [ROLES.CUSTOMER]: [
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.CATEGORIES_READ,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_CANCEL
  ],

  [ROLES.SUPPORT]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.ORDERS_READ
  ],

  [ROLES.AUDITOR]: [
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.REPORTS_READ
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.PAYMENTS_READ,
    PERMISSIONS.REFUNDS_READ
  ],

  [ROLES.MARKETING]: [
    PERMISSIONS.ANALYTICS_READ
  ],

  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.INVENTORY_MANAGE
  ],

  [ROLES.DEMO]: [
    PERMISSIONS.PRODUCTS_READ
  ]

});

module.exports = {
  ROLE_PERMISSIONS
};
